# Generated by Django 3.0.6 on 2020-07-31 06:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=45)),
                ('category_code', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('category_desc', models.CharField(max_length=200)),
                ('list_count', models.IntegerField(blank=True, null=True)),
                ('authority', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'board_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoardLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'board_likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoardReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('reference_reply_id', models.IntegerField(blank=True, null=True)),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'board_replies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
                ('bookdata', models.CharField(default=None, max_length=100)),
                ('docfile', models.FileField(blank=True, upload_to='documents/%Y/%m/%d')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
            ],
            options={
                'db_table': 'boards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Booklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'booklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cart',
                'ordering': ['created'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cartitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cartitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_name', models.CharField(max_length=100)),
                ('dis_amount', models.IntegerField()),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '쿠폰-일반',
                'verbose_name_plural': '쿠폰-일반',
                'db_table': 'coupon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CouponUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'coupon_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Onlineclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catename', models.CharField(max_length=100)),
                ('catenum', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '온라인-주제',
                'verbose_name_plural': '온라인-주제',
                'db_table': 'onlineclass',
                'ordering': ['catenum'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Onlinemovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('merchant_id', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
            ],
            options={
                'verbose_name': '동영상목록',
                'verbose_name_plural': '동영상목록',
                'db_table': 'onlinemovie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Onlineuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'onlineuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_region', models.CharField(max_length=20)),
                ('school_id', models.CharField(max_length=10)),
                ('school_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '학교목록',
                'verbose_name_plural': '학교목록',
                'db_table': 'schools',
                'ordering': ['school_region', 'school_id', 'school_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schoolusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'schoolusers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_superuser', models.IntegerField()),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=254)),
                ('date_of_birth', models.DateTimeField()),
                ('date_joined', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.IntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('coupon', models.ManyToManyField(blank=True, through='boardapp.CouponUser', to='boardapp.Coupon')),
                ('onlineclass', models.ManyToManyField(blank=True, through='boardapp.Onlineuser', to='boardapp.Onlineclass')),
                ('schools', models.ManyToManyField(blank=True, through='boardapp.Schoolusers', to='boardapp.Schools')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='Onlineorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('transaction_status', models.CharField(max_length=100)),
                ('pay_type', models.CharField(max_length=10)),
                ('crated_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boardapp.User')),
            ],
            options={
                'verbose_name': '결제정보',
                'verbose_name_plural': '결제정보',
                'db_table': 'onlineorder',
            },
        ),
    ]
